### ISSUE TITLE
Road to v1.0.0

### ISSUE THREAD

**Issue by kkAyataka** [kkAyataka/sphinxcontrib-xlsxtable#11]
## ToDo

- [x] Implements `start-row` option ( #12 )
- [x] Implements `start-column` option
- [x] Implements `include_columns` option
- [x] Implements `exclude_columns` option
